### ISSUE TITLE
dll name on windows

### ISSUE THREAD

**Issue by reedjones** [nwhitehead/pyfluidsynth#11]
On my windows machine the dll name is "libfluidsynth64"

had to add this line at the top:

`lib = find_library('libfluidsynth64')`

I also removed the "set reverb full" and "set chorus full" functions, because they aren't present in that dll and gave me errors..

**Comment by ChristianRomberg** [comment]
Is this an issue for all windows installations of fluidsynth? I'd be
surprised because AFAIK the reverb and chorus functions you mentioned are
part of all recent binaries.

Reed <notifications@github.com> schrieb am Do., 26. Juli 2018, 10:14:

**Comment by reedjones** [comment]
Hmm, yeah I think it might be a windows thing. I tried it with multiple different versions.

**Comment by ChristianRomberg** [comment]
Hm. I haven't found any fluidsynth installer for windows online, and for me (without a windows installation) testing would be pretty awful. I think one way to solve this is to pack known good&tested fluidsynth binaries into the wheel. What do you think? @nwhitehead

**Comment by nwhitehead** [comment]
I'm OK with including the DLL for Windows wheels (maybe with a special name). I don't have convenient Windows access to do this, sorry.

**Comment by Laubeee** [comment]
@ChristianRomberg well yes unfortunately there are no binaries for fluidsynth. However fluidsynth 1.1.10 is available through [vcpkg](https://docs.microsoft.com/en-us/cpp/vcpkg?view=vs-2017) which is fairly easy to install and then you can just use:
`vcpkg install fluidsynth` (make sure you use the `--triplet x64-windows` option for x64 build.)

on a side note: i couldn't get your demo to work (play a chord for 1s with noteon). It runs through but nothing is audible... any idea why? fluidsynth itself seems to work as expected when i play a midi file with the same .sf2 file

**Comment by Laubeee** [comment]
Sorry for the late reply. I didn't see that test file, I was talking about your demo in the readme file, where there is no mention about drivers.
Since I am on Windows I don't have alsa, but I have Direct Sound. However when I specify that I got:

`fluidsynth: error: Couldn't find the requested audio driver Direct Sound. Valid drivers are: dsound, file.`

So I tried dsound, which gave an error in your assert statement (which I think you should remove completely as there is already an error from fluidsynth when the driver cannot be found).
When I added dsound to your list of options for assert, it worked :) thanks for the hint

**Comment by albedozero** [comment]
Most of the issues raised in this thread seem to have been fixed by solving #12, #15, and #19. OP's problem with finding the correct DLL name might have to do with how the FluidSynth binaries were obtained (i.e. installing QSynth or something like). I think @ChristianRomberg 's comment about adding FS binaries to the wheel is a good idea and deserves its own issue, so I'm closing here.
